[[questions]]
question = """
Hva er en dyd, og hva har dydene med god moralsk handling å gjøre,
ifølge dydsetikken? Gi eksempler på dyder som ikke står i
*Tenk!*-boken. 
"""

[[questions.answers]]
ans = """
Dyder er ikke bare positive egenskaper. En dyd er gode
karaktertrekk som former den man er og hvordan man handler.
Moral er noe vi lærer gjennom erfaring, og som innebærer at vi
utvikler dydige karaktertrekk over tid. Et sentralt poeng for
dydsetikken er at spørsmålet om gode handlinger må ses i
sammenheng med den moralske aktørens liv og situasjon (Antonsen
et al., 2023, s. 258). Det vil si at handlinger som er i samsvar
med dydene vil være moralsk riktige og gode eller dårlig og
galt. Et eksempel på en dyd kan være medfølelse. Et eksempel på
dette i praksis- at man legger merke til at en venn har det
dårlig og kan virke nedfor. En god dyd ville da vært å spurt
vennen hvordan de har det og lyttet etter det vedkommende har på
hjertet. 
"""

[[questions.answers]]
ans = """
«Dyd er positive karaktertrekk eller egenskaper som disponerer
oss til å handle på bestemte måter» (Antonsen et al.s.265). I
dydsetikken så legger man ikke vekt på moralske regler og
konsekvenser, men man handler ut fra «hvilken person jeg ønsker
å være». Man tar altså ikke i betraktning hva som er den
moralske etikken når vi tenker på dydsetikk, men heller hva som
er riktig handling i den ebstemte situasjonen. Eksempel på dyder
er for eksempel å være en omsorgsfull person og en generøs
person. Det er å handle riktig ut fra situasjon. For eksempel
kan det være en dyd å si fra om noen stjeler. Men i en annen
situasjon kan det være en dyd å ikke si fra dersom noen stjeler.
Alt etter hva handlingen fører til. (Antonsen et al.s.265). 
"""

[[questions.answers]]
ans = """
En dyd er et positivt karaktertrekk som anses som moralsk
verdifullt, som fører til at vi handler på en viss måte (1, s.
262). Dersom en person står opp for og støtter noen de ser blir
ignorert eller gjort narr av, viser de både mot og
rettferdighet.
"""

[[questions]]
question = """
Hva er forholdet mellom dyd og lykke, ifølge dydsetikk? 
"""

[[questions.answers]]
ans = """
Et vesentlig trekk ved dydsetikken er at vi ikke bare bør strebe
etter å være dydige fordi det får oss til å handle riktig i møte
med andre, men fordi dydene bidrar til at vi fungerer godt og
lever gode liv. (Antonsen et al., 2025, s. 264). Spørsmålet på
hva som utgjør et vellykket liv, er vanskelig å svare på, men vi
kan se for oss at det for eksempel handler om å ha gode
relasjoner og bruke tiden sin på meningsfulle aktiviteter.
(Antonsen et al., 2025, s. 264)
"""

[[questions.answers]]
ans = """
Ifølge dydsetikken vil man kunne oppnå eudaimonia, det gode liv,
dersom man lever et dydig liv (1, s. 264). Man vil altså ifølge
dydsetikken og Aristoteles leve et lykkelig liv ved å fokusere
på å leve best mulig, og bli den beste mulige versjonen av seg
selv ved å handle dydig.
"""

[[questions.answers]]
ans = """
Lykke (eudaimonia) er målet og formålet med alt vi gjør.
Begrepet Aristoteles bruker når han skriver om dette er
eudaimonia (Antonsen et al. 2023, s. 264) Det beskriver livet
som en helhet for hvordan vi skal leve et godt liv å lykkes som
mennesker. Dyd er nødvendig for og den viktigste delen av lykke.
Det er nøkkelen til å at man får et meningsfullt liv. Et godt
liv krever dyder, men dydene alene er ikke nok (Antonsen et al.
2023, s. 264).
"""

[[questions]]
question = """
Enkelte har innvendt mot dydsetikken at den er vanskelig å anvende i
praksis. Er du enig i innvendingen? 
"""

[[questions.answers]]
ans = """
Jeg kan forstå at det kan være vanskelig å forholde seg til
dydsetikken i praksis, men jeg mener at dydsetikken gir en god
handlingsveiledning på hva man burde gjøre i et dilemma. Selv om
dydsetikken ikke har konkrete svar på etiske dilemmaer, så kan
utfordringen likevel fortelle oss om hvordan vi bør handle. For
eksempel Rosalind Hursthouse (1943-) har argumenter for dette:
Når vi sier om en handling at den er uansvarlig, for eksempel,
har vi jo samtidig sagt noe om hvorvidt det er noe man bør gjøre
eller ei. (Antonsen et al., 2023, s. 265). Dydsetikken forklarer
at vi skal gjøre det som er respektfullt og det som er ærlig, og
at vi ikke skal gjøre det som er gjerrig eller feigt (Antonsen
et la., 2023, s. 265). Ut ifra disse dydsreglene, så har vi fått
en form for handlingsveiledning fra dydsetikken.  
"""

[[questions.answers]]
ans = """
Ja, noen ganger kan dydige handlinger sette oss i vanskelig
situasjoner. F.eks Nelson Mandela som utviste stort mot gjennom
sin aktivisme mot aparheid i Sør-Afrika, og som satt i fengsel i
27 år under harde forhold som er langt unna det vi vanligvis
forbinder med lykke (Christensen, 2008, s 49). Sammenhengen
mellom dyd å lykke kan derfor virke kontraintuitiv. (Antonsen et
al., 2025, s. 264)
"""

[[questions.answers]]
ans = """
Jeg er nokså enig i denne innvendingen. Dydsetikken gir nemlig
ingen fasit på akkurat hva som er ansett som dydig i en
situasjon, og det er derfor opp til enhver å vurdere dette selv.
I eksempelet gitt i Tenk! Fra Victor Hugo sin roman De elendige
blir valget Jean Valjeans tatt ansett som dydig med tanke på at
han er omsorgsfull og ansvarsfull ovenfor sin familie (Antonsen
et al., 2025, s.258-259). Samtidig kan man argumentere at det
hadde vært mer dydig av han å skaffe maten på en mer ærlig måte
enn tyveri. I tillegg til at dydsetikken er preget av menneskets
subjektive perspektiv, er det ikke alltid like lett i praksis.
Det mest dydige valget er ikke alltid det som frister mest,
eller det som virker til å ha det beste utfallet.
"""
